--- #YAML:1.0
name:                HTML-Tiny
version:             0.8
abstract:            Lightweight, dependency free HTML/XML generation
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
